/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.penyewa;

import controller.AuthController;
import controller.MobilController;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import util.ArraySewa;

/**
 *
 * @author user
 */
public class FormPenyewaan extends javax.swing.JFrame {

    private static AuthController authController;
    private static MobilController mobilController;

    Icon iconsucces = new javax.swing.ImageIcon(getClass().getResource("/img/icon_berhasil.jpg"));
    Icon iconfield = new javax.swing.ImageIcon(getClass().getResource("/img/icon_delete.jpg"));

    /**
     * Creates new form FormPenyewaan
     */
    public FormPenyewaan() {
        initComponents();
        if (mobilController.mobilQueueIsEmpty() == false) {
            txtx_namaMobil.setText(mobilController.peekNamaMobil());
        } else {
            txtx_namaMobil.setText("Tidak ada mobil yang tersedia");
        }
        txtUsername.setText(authController.getUsername());

        txt_lamaSewa.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTextHarga();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTextHarga();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Plain text components don't fire these events.
            }

            private void updateTextHarga() {
                // Mengisi textField2 dengan nilai dari textField1
                if (txt_lamaSewa.getText() != null) {
                    int hargaSewa = Integer.parseInt(txt_lamaSewa.getText()) * 100000;
                    String StringHargaSewa = Integer.toString(hargaSewa);
                    txt_harga.setText(StringHargaSewa);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtx_namaMobil = new CustomGui.FTextField();
        txt_lamaSewa = new CustomGui.FTextField();
        txt_harga = new CustomGui.FTextField();
        fButton1 = new CustomGui.FButton();
        btn_penyewaan = new CustomGui.FButton();
        btn_pengembalian = new CustomGui.FButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(42, 43, 82));
        txtUsername.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.setEnabled(false);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 188, 140, 25));

        txtx_namaMobil.setEnabled(false);
        txtx_namaMobil.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtx_namaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtx_namaMobilActionPerformed(evt);
            }
        });
        getContentPane().add(txtx_namaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 350, 50));

        txt_lamaSewa.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_lamaSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lamaSewaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_lamaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 350, 50));

        txt_harga.setEnabled(false);
        txt_harga.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 350, 50));

        fButton1.setBackground(new java.awt.Color(51, 204, 0));
        fButton1.setText("SEWA");
        fButton1.setFillClick(new java.awt.Color(52, 152, 219));
        fButton1.setFillOriginal(new java.awt.Color(51, 204, 0));
        fButton1.setFillOver(new java.awt.Color(51, 153, 0));
        fButton1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        fButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(fButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 330, 50));

        btn_penyewaan.setText("Penyewaan");
        btn_penyewaan.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_penyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penyewaanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_penyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 235, 40));

        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 235, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/Form Pemesanan (penyewa) newwwwww.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtx_namaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtx_namaMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtx_namaMobilActionPerformed

    private void txt_lamaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lamaSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lamaSewaActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void fButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton1ActionPerformed
        boolean status = mobilController.addSewa(Integer.parseInt(txt_lamaSewa.getText()));
        if (status == true) {
            JOptionPane.showMessageDialog(null,  "<html><b style=\"color:green; font-size:15px; "
                    + "background-color:white;\">Mobil Berhasil Disewa<b></html>", "Sewa succes", 0, iconsucces);
        } else {
            JOptionPane.showMessageDialog(null,  "<html><b style=\"color:green; font-size:15px; "
                    + "background-color:white;\">Mobil Tidak Tersedia<b></html>", "Sewa fail", 0, iconfield);
        }
        new FormPenyewaan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fButton1ActionPerformed

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        // TODO add your handling code here:
        ArraySewa arraySewa = mobilController.getArraySewa();
        if (arraySewa == null) {
            JOptionPane.showMessageDialog(null, "Anda Belum Menyewa Mobil", "Pengembalian field", 0, iconfield);
        } else {
            new Pengembalian().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void btn_penyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penyewaanActionPerformed
        
    }//GEN-LAST:event_btn_penyewaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenyewaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomGui.FButton btn_pengembalian;
    private CustomGui.FButton btn_penyewaan;
    private CustomGui.FButton fButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtUsername;
    private CustomGui.FTextField txt_harga;
    private CustomGui.FTextField txt_lamaSewa;
    private CustomGui.FTextField txtx_namaMobil;
    // End of variables declaration//GEN-END:variables
}
