/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.penyewa;

import controller.AuthController;
import javax.swing.table.DefaultTableModel;
import model.SewaModel;
import util.ArraySewa;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import controller.MobilController;
import java.sql.Timestamp;
import java.time.Instant;
import javax.swing.Icon;

/**
 *
 * @author user
 */
public class Pengembalian extends javax.swing.JFrame {

    private static AuthController authController;
    private static MobilController mobilController;
    Icon iconsucces = new javax.swing.ImageIcon(getClass().getResource("/img/icon_berhasil.jpg"));
    Icon iconfield = new javax.swing.ImageIcon(getClass().getResource("/img/icon_delete.jpg"));

    /**
     * Creates new form MobilTersedia
     */
    public Pengembalian() {
        initComponents();
        txt_Username.setText(authController.getUsername());
        tampilkanData();
        centerWindow();
    }

    public void tampilkanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Sewa");
        model.addColumn("Nama Mobil");
        model.addColumn("Tanggal Sewa");
        model.addColumn("Tanggal Pengembalian");
        model.addColumn("ID Mobil");
        ArraySewa arraySewa = mobilController.getArraySewa();
        for (int i = 0; i < arraySewa.getnElemen(); i++) {
            SewaModel sewa[] = arraySewa.getArrSewa();
            Object[] rowData = {sewa[i].getIDSewa(), sewa[i].getNamaMobil(), sewa[i].getTglSewa(),
                sewa[i].getTglPengembalian(), sewa[i].getIDMobil()};
            model.addRow(rowData);
        }
        tabelPengembalian.setModel(model);
    }

    private void centerWindow() {
        int screenWidth = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int screenHeight = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

        int frameWidth = getWidth();
        int frameHeight = getHeight();

        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;

        setLocation(x, y);
    }

    public class TanggalPengembalian {

        private LocalDateTime tglPengembalian;

        public TanggalPengembalian(LocalDateTime tglPengembalian) {
            this.tglPengembalian = tglPengembalian;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Username = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPengembalian = new javax.swing.JTable();
        txt_idMobil = new CustomGui.FTextField();
        txt_tanggalPenyewaan = new CustomGui.FTextField();
        txt_namaMobil = new CustomGui.FTextField();
        txt_tanggalPengembalian = new CustomGui.FTextField();
        txt_keterlambatan = new CustomGui.FTextField();
        btn_kembalikan = new CustomGui.FButton();
        btn_penyewaan = new CustomGui.FButton();
        btn_pengembalian = new CustomGui.FButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Username.setBackground(new java.awt.Color(42, 43, 82));
        txt_Username.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_Username.setForeground(new java.awt.Color(255, 255, 255));
        txt_Username.setBorder(null);
        txt_Username.setEnabled(false);
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 185, 120, 25));

        tabelPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPengembalian);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 400, 710, 250));

        txt_idMobil.setEnabled(false);
        txt_idMobil.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_idMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idMobilActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 200, 45));

        txt_tanggalPenyewaan.setEnabled(false);
        txt_tanggalPenyewaan.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_tanggalPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalPenyewaanActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tanggalPenyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 200, 45));

        txt_namaMobil.setEnabled(false);
        txt_namaMobil.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_namaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaMobilActionPerformed(evt);
            }
        });
        getContentPane().add(txt_namaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 200, 45));

        txt_tanggalPengembalian.setEnabled(false);
        txt_tanggalPengembalian.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_tanggalPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalPengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tanggalPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 200, 45));

        txt_keterlambatan.setEnabled(false);
        txt_keterlambatan.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_keterlambatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keterlambatanActionPerformed(evt);
            }
        });
        getContentPane().add(txt_keterlambatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 200, 45));

        btn_kembalikan.setText("Kembalikan");
        btn_kembalikan.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        btn_kembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembalikanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembalikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 295, 160, 40));

        btn_penyewaan.setText("Penyewaan");
        btn_penyewaan.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_penyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penyewaanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_penyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 235, 40));

        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        getContentPane().add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 235, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/Pengembalian neww(penyewa).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed

    private void txt_idMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idMobilActionPerformed

    private void btn_penyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penyewaanActionPerformed
        // TODO add your handling code here:
        new FormPenyewaan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_penyewaanActionPerformed

    private void tabelPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengembalianMouseClicked
        // TODO add your handling code here:
        int tabel = tabelPengembalian.getSelectedRow();
        txt_idMobil.setText(tabelPengembalian.getValueAt(tabel, 0).toString());
        txt_namaMobil.setText(tabelPengembalian.getValueAt(tabel, 1).toString());
        txt_tanggalPenyewaan.setText(tabelPengembalian.getValueAt(tabel, 2).toString());
        txt_tanggalPengembalian.setText(tabelPengembalian.getValueAt(tabel, 3).toString());
        Instant currentInstant = Instant.now();
        Timestamp sekarang = Timestamp.from(currentInstant);
        Timestamp tanggalPengembalian = Timestamp.valueOf(txt_tanggalPengembalian.getText());
        int perbandingan = sekarang.compareTo(tanggalPengembalian);
        if (perbandingan > 0) {
            txt_keterlambatan.setText("Terlambat");
        }else{
            txt_keterlambatan.setText("Belum Terlambat");
        }
    }//GEN-LAST:event_tabelPengembalianMouseClicked

    private void txt_tanggalPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalPenyewaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalPenyewaanActionPerformed

    private void txt_namaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaMobilActionPerformed

    private void txt_tanggalPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalPengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalPengembalianActionPerformed

    private void txt_keterlambatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keterlambatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keterlambatanActionPerformed

    private void btn_kembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembalikanActionPerformed
        boolean status = mobilController.setPengembalian(txt_idMobil.getText());
        if (status == true) {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:green; font-size:15px; "
                    + "background-color:white;\">Mobil Berhasil Dikembalikan<b></html>", "Pengembalian succes", 0, iconsucces);
            new Pengembalian().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:green; font-size:15px; "
                    + "background-color:white;\">Mobil Gagal Dikembalikan<b></html>" , "Pengembalian field", 0, iconfield);
            new Pengembalian().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_kembalikanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomGui.FButton btn_kembalikan;
    private CustomGui.FButton btn_pengembalian;
    private CustomGui.FButton btn_penyewaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPengembalian;
    private javax.swing.JTextField txt_Username;
    private CustomGui.FTextField txt_idMobil;
    private CustomGui.FTextField txt_keterlambatan;
    private CustomGui.FTextField txt_namaMobil;
    private CustomGui.FTextField txt_tanggalPengembalian;
    private CustomGui.FTextField txt_tanggalPenyewaan;
    // End of variables declaration//GEN-END:variables
}
