/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AuthController;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import view.penyewa.Pengembalian;
/**
 *
 * @author Lenovo
 */
public class Register extends javax.swing.JFrame {
    
    private static AuthController authController;
    Icon iconsucces = new javax.swing.ImageIcon(getClass().getResource("/img/icon_berhasil.jpg"));
    Icon iconfield = new javax.swing.ImageIcon(getClass().getResource("/img/icon_delete.jpg"));
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new CustomGui.FTextField();
        txtAlamat = new CustomGui.FTextField();
        txtNoHP = new CustomGui.FTextField();
        txtNoKtp = new CustomGui.FTextField();
        btnRegister = new CustomGui.FButton();
        txtPassword = new CustomGui.FTextField();
        btnKemali = new CustomGui.FButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 220, 40));

        txtAlamat.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 220, 40));

        txtNoHP.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtNoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHPActionPerformed(evt);
            }
        });
        getContentPane().add(txtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 395, 220, 40));

        txtNoKtp.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtNoKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoKtpActionPerformed(evt);
            }
        });
        getContentPane().add(txtNoKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 455, 220, 40));

        btnRegister.setText("REGISTER");
        btnRegister.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 340, 50));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 220, 40));

        btnKemali.setText("KEMBALI");
        btnKemali.setFillClick(new java.awt.Color(255, 0, 0));
        btnKemali.setFillOriginal(new java.awt.Color(153, 0, 0));
        btnKemali.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btnKemali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKemaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKemali, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, 340, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/registerNewww.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHPActionPerformed

    private void txtNoKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoKtpActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String noKTP = txtNoKtp.getText();
        String alamat = txtAlamat.getText();
        String noHP = txtNoHP.getText();
        boolean status =  authController.register(username, password, noKTP, alamat, noHP);
        if (status == true) {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:green; font-size:15px; "
                    + "background-color:white;\">Registrasi Berhasil<b></html>", "Pengembalian succes", 0, iconsucces);
        } else {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:red; font-size:15px; "
                    + "background-color:white;\">Registrasi Gagal<b></html>", "Pengembalian field", 0, iconfield);
            new Pengembalian().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnKemaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKemaliActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKemaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomGui.FButton btnKemali;
    private CustomGui.FButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private CustomGui.FTextField txtAlamat;
    private CustomGui.FTextField txtNoHP;
    private CustomGui.FTextField txtNoKtp;
    private CustomGui.FTextField txtPassword;
    private CustomGui.FTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
