/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import controller.AuthController;
import controller.MobilController;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import view.penyewa.FormPenyewaan;

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    private static AuthController authController;
    private static MobilController mobilController;

    Icon iconsucces = new javax.swing.ImageIcon(getClass().getResource("/img/icon_berhasil.jpg"));
    Icon iconfield = new javax.swing.ImageIcon(getClass().getResource("/img/icon_delete.jpg"));

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        centerWindow();
    }

    private void centerWindow() {
        int screenWidth = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int screenHeight = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

        int frameWidth = getWidth();
        int frameHeight = getHeight();

        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;

        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Login = new CustomGui.FButton();
        txt_Password = new CustomGui.FTextField();
        txt_Username = new CustomGui.FTextField();
        btnRegister = new CustomGui.FButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Login.setText("LOGIN");
        btn_Login.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 330, 50));

        txt_Password.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 330, 50));

        txt_Username.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 330, 50));

        btnRegister.setText("REGISTER");
        btnRegister.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 330, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/Group 344.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        boolean status = authController.login(txt_Username.getText(), txt_Password.getText());
        if (status == true) {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:green; font-size:15px; "
                    + "background-color:white;\">ANDA BERHASIL LOGIN<b></html>", "Login Succes", 
                    0, iconsucces);
            int role = authController.getRole();
            if (role == 1) {
                new FormPenyewaan().setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:red; font-size:15px;"
                    + "\">Username Tidak Terdaftarkan<b></html>", "Login field", 0, iconfield);
            txt_Username.setText("");
            txt_Password.setText("");
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        Register rgs = new Register();
        rgs.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomGui.FButton btnRegister;
    private CustomGui.FButton btn_Login;
    private javax.swing.JLabel jLabel1;
    private CustomGui.FTextField txt_Password;
    private CustomGui.FTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
